# Generated by Django 3.2.16 on 2023-05-18 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CLIENT', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='AgrGPT/static/message_images/'),
        ),
    ]
